/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RscssOptions {
  rule: string
}
export interface RscssGenerator {
  options: RscssOptions
}
export function createGenerator(options: RscssOptions): RscssGenerator
